app/Http/routes.php
<?php
Route::get('/', 'HomeController@index')->name('home');
Route::get('register', function(){ return View::make('register')->with('pTitle', "Register"); })->name('register');
Route::get('login', function(){ return View::make('login')->with('pTitle', "Login"); })->name('login');
Route::get('faq', function(){ return View::make('faq')->with('pTitle', "FAQ"); })->name('faq');

//----------------- User routes
Route::resource('users', 'UsersController', array('only' => array('show')));
Route::post('login', 'UsersController@login');
Route::post('make', 'UsersController@register');
Route::get('logout', 'UsersController@logout')->name('logout');
Route::post('resetPassword/{id}','UsersController@resetPassword');

//----------------- Issues routes
Route::resource('issues', 'IssuesController@index');
Route::post('login', 'UsersController@login');
Route::post('make', 'UsersController@register');
Route::get('logout', 'UsersController@logout')->name('logout');
Route::post('resetPassword/{id}','UsersController@resetPassword');

//----------------- Auth routes
Route::group(array('before' => 'auth'), function()
{
	Route::get('hud', 'HomeController@index')->name('hud');
	Route::get('search', 'HomeController@search')->name('search');
	Route::get('profile', 'UsersController@index')->name('profile');
	Route::get('clients', 'ClientsController@index')->name('clients');
	Route::delete('clients/{id}', 'ClientsController@destroy');
    Route::resource('projects', 'ProjectsController', array('only' => array('show')));


Route::delete('projects/{id}/remove', array('uses' => 'ProjectsController@remove', 'as' => 'projects.remove') );
Route::get('projects/{id}/files', array('uses' => 'ProjectsController@files', 'as' => 'projects.files' ));
Route::post('projects/{id}/files', array('uses' => 'FilesController@store', 'as' => 'files.store' ));
Route::delete('projects/{id}/files', array('uses' => 'FilesController@destroy', 'as' => 'files.remove' ));
});

//----------------- API routes
Route::group(['prefix' => '/api/'], function()
{	
	// USER 
    Route::get('user', 'UsersController@getUser');
    Route::post('user/{id}', 'UsersController@updateUser');
	Route::delete('user/', 'UsersController@deleteUser');

	// CLIENT
	Route::get('clients/{withWeight?}', 'ClientsController@getAllUserClients');
    Route::get('clients/id/{id}', 'ClientsController@retrieveClient');
	Route::put('clients/{id}', 'ClientsController@updateClient');
	Route::post('clients', 'ClientsController@storeClient');
	Route::delete('clients/{id}', 'ClientsController@removeClient');

	// PROJECT
    Route::get('projects/', 'ProjectsController@getAllUserProjects');
    Route::get('projects/shared', 'ProjectsController@getAllMemberProjects');
    Route::get('projects/{id}','ProjectsController@getProject');
    Route::get('projects/{id}/owner','ProjectsController@getOwner');
    Route::get('projects/{id}/members','ProjectsController@getMembers');
	Route::post('projects', 'ProjectsController@storeProject');
    Route::put('projects/{id}', 'ProjectsController@updateProject');
    Route::post('projects/{id}/{email}/invite', 'ProjectsController@invite');
    Route::delete('projects/{id}/{member_id}/remove', 'ProjectsController@removeMember' );

	// TASK
    Route::get('tasks', 'TasksController@getAllUserOpenTasks');
    Route::post('tasks/{client_id}/{project_id}', 'TasksController@storeTask');
    Route::delete('tasks/{id}', 'TasksController@removeTask');
    Route::put('tasks/{id}', 'TasksController@updateTask');

	// CREDENTIALS
    Route::get('credentials/{id}','CredentialsController@getProjectCredentials');
    Route::post('credentials', 'CredentialsController@storeCredential');
    Route::put('credentials/{id}', 'CredentialsController@updateCredential');
    Route::delete('credentials/{id}', 'CredentialsController@removeCredential');
});

//----------------- Admin routes
Route::get('admin','AdminController@index');

resources/views/ins/hud.blade.php
@extends('templates/ins/master')

@section('content')
	<div class="row" xmlns:v-on="http://www.w3.org/1999/xhtml" xmlns:v-on="http://www.w3.org/1999/xhtml"
		 xmlns:v-on="http://www.w3.org/1999/xhtml">
		<div class="col-xs-12 page-title-section">
			<h1 class="pull-left">Hud</h1>
		</div>
	</div>

	<div id="hud" class="row">
        <div class="col-xs-12 col-sm-4">
            <div class="jumbotron text-center">
                <p class="dim">Clients</p>
                <h1>@{{ clients }}</h1>
            </div>
        </div>
        <div class="col-xs-12 col-sm-4">
            <div class="jumbotron text-center">
                <p class="dim">Projects</p>
                <h1>@{{ projects.length }}</h1>
            </div>
        </div>
        <div class="col-xs-12 col-sm-4">
            <div class="jumbotron text-center">
                <p class="dim">Tasks</p>
                <h1>@{{ tasks }}</h1>
            </div>
        </div>

        <div class="col-xs-6">
            <div class="project-list-container">
                <template v-if="projects.length > 0">
                    <h4>My Projects</h4>
                    <input placeholder="Search projects" type="text" class="form-control" v-model="my_project_text">
                    <hr>
                    <table class="table table-striped">
                        <thead>
                        <tr>
                            <th>#</th>
                            <th>Name</th>
                            <th>Progress</th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr v-for="project in projects | filterBy my_project_text">
                            <td>@{{ $index + 1 }}</td>
                            <td><a href="{{ route('projects.show', ['id' => '']) }}/@{{ project.id }}">@{{ project.name }}</a></td>
                            <td>
                                <div class="progress">
                                    <div class="progress-bar" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width:@{{ project.completedWeight / project.totalWeight * 100 }}%;">
                                    </div>
                                </div>
                            </td>
                        </tr>
                        </tbody>
                    </table>
                </template>

                <template v-if="projects.length == 0">
                    <p class="alert alert-warning">
                        Your projects will be listed here once you create some.
                        Create a new project within the <a href="{{ route('clients') }}">clients</a> page.
                    </p>
                </template>
            </div>
        </div>

        <div class="col-xs-6">
            <div class="project-list-container">
                <template v-if="sharedProjects.length > 0">
                    <h4>Projects Shared With Me</h4>
                    <input placeholder="Search projects" type="text" class="form-control" v-model="my_sproject_text">
                    <hr>
                    <table class="table table-striped">
                        <thead>
                        <tr>
                            <th>#</th>
                            <th>Name</th>
                            <th>Progress</th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr v-for="project in sharedProjects | filterBy my_sproject_text">
                            <td>@{{ $index + 1 }}</td>
                            <td><a href="{{ route('projects.show', ['id' => '']) }}/@{{ project.id }}">@{{ project.name }}</a></td>
                            <td>
                                <div class="progress">
                                    <div class="progress-bar" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width:@{{ project.completedWeight / project.totalWeight * 100 }}%;">
                                    </div>
                                </div>
                            </td>
                        </tr>
                        </tbody>
                    </table>
                </template>

                <template v-if="sharedProjects.length == 0">
                    <p class="alert alert-warning">
                        Projects that you have been invited to will show up here. Currently
                        you have not been invited to any project.
                    </p>
                </template>
            </div>
        </div>

    </div>

	<div id="client" class="popup-form new-client">
		<header>
			<p class="pull-left">New Client</p>
			<div class="actions pull-right">
				<i title="Minimze " class="ion-minus-round"></i>
				<i title="Close" class="ion-close-round"></i>
			</div>
			<div class="clearfix"></div>
		</header>
		<section>
			<form>
				<span class="status-msg"></span>
				<input v-model="client.name" placeholder="Client Name" type="text" class="form-control">
				<input v-model="client.email" placeholder="Email" type="text" class="form-control">
				<input v-model="client.point_of_contact" placeholder="Point Of Contact" type="text" class="form-control">
				<input v-model="client.phone_number" placeholder="Contact Number" type="text"class="form-control">
			</form>
		</section>
		<footer>
			<a v-on:click="create(client)" href="" class="btn btn-primary pull-right">Save</a>
			<div class="clearfix"></div>
		</footer>
	</div>
    <script src="{{ asset('assets/js/controllers/hud.js') }}"></script>

@stop()

resources/views/ins/search.blade.php
@extends('templates/ins/master')

@section('content')
	<div class="row">
		<div class="col-xs-12 page-title-section">
			<h1 class="pull-left">Search</h1>
		</div>
		<div class="col-xs-12">
			<strong class="color-primary">
				{{ count($clients) + count($projects) + count($tasks) }}
			</strong>Results for: "<strong class="color-primary"><i>{{ $q }}</i></strong>"</h4><br><br>
		</div>
	</div>

	<div class="row">

		<div class="col-xs-12">
			{{-- clients --}}
			<div class="panel panel-default panel-list">
			  <div class="panel-heading">Clients ({{count($clients)}})</div>
			  <div class="panel-body">
			  	@if (count($clients) > 0)
				  	@foreach ($clients as $client)
				  		<a href="{{ route('clients', ['id' => $client->id]) }}">
				  			{{ $client->name }}
				  		</a>
				  	@endforeach			  			  	
				@else
				    <section class="info">
						<p class="dimmed">Sorry I couldn't find nothing....</p>	
				    </section>
			  	@endif
			  </div>
			</div>			

			{{-- projects --}}
			<div class="panel panel-default panel-list">
			  <div class="panel-heading">Projects ({{count($projects)}})</div>
			  <div class="panel-body">
			  	@if (count($projects) > 0)
				  	@foreach ($projects as $project)
				  		<a href="{{ route('projects.show', ['id' => $project->id]) }}">
				  			{{ $project->name }}
				  			<span class="weight pull-right">w.{{ $project->totalWeight()}}</span>
				  		</a>
				  	@endforeach			  			  	
				@else
				    <section class="info">
						<p class="dimmed">Sorry I couldn't find nothing....</p>	
				    </section>
			  	@endif
			  </div>
			</div>

			{{-- tasks --}}
			<div class="panel panel-default panel-list">
			  <div class="panel-heading">Tasks ({{count($tasks)}})</div>
			  <div class="panel-body">
			  	@if (count($tasks) > 0)
				  	@foreach ($tasks as $task)
				  		<a href="{{ route('projects.show', ['id' => $task->project_id]) }}">
				  			{{ $task->name }}
				  			<span class="weight pull-right">w.{{ $task->weight}}</span>
				  		</a>
				  	@endforeach			  			  	
				@else
					  <section class="info">
						  <p class="dimmed">Sorry I couldn't find nothing....</p>
					  </section>
			  	@endif
			  </div>
			</div>			
	
		</div>
	</div>

@stop()

resources/views/ins/settings.blade.php
@extends('templates/ins/master')

@section('content')
    <div id="user">
        <div class="row">
            <div class="col-xs-12 page-title-section">
                <h1 class="pull-left">Settings</h1>
                <a v-on:click="update()" class="btn btn-primary pull-right" title="Create new client">Save Changes</a>
                <div class="clearfix"></div>
            </div>
        </div>

        <div class="row settings-container">
            <div class="col-xs-12">
                <section>
                <div class="col-xs-12 col-md-4 left-side">
                    <a href="{{ route('profile') }}"><img class="circle" src="{{ App\User::get_gravatar(Auth::user()->email) }}"></a>
                    <div class="info">
                        <p class="name">@{{ user.full_name }}</p>
                        <p class="color-primary">@{{ user.email }}</p>
                        <p class="color-primary">@{{ user.title }}</p>
                    </div>
                    <div class="clearfix"></div>
                    <br>
                    <div class="links">
                        <p v-if="user.link">
                            <a target="_blank" href="">
                                <span class="ion-ios-world-outline"></span> @{{ user.link }}
                            </a>
                        </p>
                        <p v-if="user.twitter">
                            <a target="_blank" href="https://twitter.com/@{{ user.twitter }}">
                                <span class="ion-social-twitter"></span> https://twitter.com/@{{ user.twitter }}
                            </a>
                        </p>
                        <p v-if="user.facebook">
                            <a target="_blank" href="https://www.facebook.com/people/@{{ user.facebook }}">
                                <span class="ion-social-facebook"></span> https://www.facebook.com/people/@{{ user.facebook}}
                            </a>
                        </p>
                        <p v-if="user.linkedin">
                            <a target="_blank" href="https://www.linkedin.com/in/@{{ user.linkedin }}">
                                <span class="ion-social-linkedin"></span> https://www.linkedin.com/in/@{{ user.linkedin }}
                            </a>
                        </p>
                    </div>
                    <hr>

                    <div class="bio">
                        <p>BIO<p>
                        <p>@{{ user.bio }}  </p>
                    </div>

                </div>
                <div class="col-xs-12 col-md-8 right-side">
                    <div class="mega-menu">
                        <p v-if="msg.error != null" class="status-msg error-msg">@{{ msg.error }}</p>
                        <p v-if="msg.success != null" class="status-msg success-msg">@{{ msg.success }}</p>
                        <div class="links">
                            <a class="" data-id="settings_info" href="">Personal Info</a>
                            <a class="" data-id="settings_links" href="">Links</a>
                            <a class="" data-id="settings" href="">Account Settings</a>
                        </div>
                        <div class="content">
                            <div class="item" id="settings_info">
                                <div class="form">
                                    <form>
                                        <div class="form-group">
                                            <label>Full Name</label>
                                            <input v-model="user.full_name" type="text" class="form-control" placeholder="Full Name">
                                        </div>
                                        <div class="form-group">
                                            <label>Email</label>
                                            <input v-model="user.email" type="text" class="form-control" placeholder="Email">
                                        </div>
                                        <div class="form-group">
                                            <label>Title</label>
                                            <input v-model="user.title" type="title" class="form-control" placeholder="Title">
                                        </div>
                                        <div class="form-group">
                                            <label>Bio</label>
                                            <textarea v-model="user.bio" class="form-control" rows="7" placeholder="A little about me.."></textarea>
                                            <br>
                                            <span class="count pull-right">@{{ 250 - user.bio.length }}</span>
                                        </div>
                                    </form>
                                </div>
                            </div>
                            <div class="item" id="settings_links">
                                <div class="input-group">
                                    <span class="input-group-addon">Link</span>
                                    <input v-model="user.link" type="text" class="form-control" placeholder="http://www.Yourwebsite.com/">
                                </div><br>
                                <div class="input-group">
                                    <span class="input-group-addon">https://twitter.com/</span>
                                    <input v-model="user.twitter" type="text" class="form-control" placeholder="username">
                                </div><br>
                                <div class="input-group">
                                    <span class="input-group-addon">https://facebook.com/</span>
                                    <input v-model="user.facebook" type="text" class="form-control" placeholder="username">
                                </div><br>
                                <div class="input-group">
                                    <span class="input-group-addon">https://Linkedin.com/</span>
                                    <input v-model="user.linkedin" type="text" class="form-control" placeholder="username">
                                </div>
                            </div>
                            <div class="item" id="settings">
                                <label>Current Password</label>
                                {!! Form::open(array('action' => array('UsersController@resetPassword', Auth::id() ))) !!}
                                <div class="form-group">
                                    {!! Form::password( 'current_pwd', array('class' => 'form-control', "placeholder" => "Current Password" )) !!}
                                </div>
                                <label>New Password</label>
                                <div class="form-group">
                                    {!! Form::password( 'new_pwd', array('class' => 'form-control', "placeholder" => "New Password" )) !!}
                                </div>
                                <div class="form-group">
                                    {!! Form::submit( 'Update Password', array('class' => 'btn btn-default pull-right')) !!}
                                    <div class="clearfix"></div>
                                </div>
                                {!! Form::close() !!}
                                <hr>
                                <label>Delete account</label>
                                <p>Enable the delete button by typing delete below</p>
                                <p class="dim">Deleting your account will delete <b>ALL</b>, clients, projects and tasks created under this account</p>
                                <input v-model="delete_text" type="text" class="form-control">
                                <br>
                                <div v-if="delete_text == 'delete' ">
                                    <button v-on:click="delete()" id="delete-account" class="btn btn-danger">Delete my account</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                </section>
            </div>
        </div>
    </div>

    <script>
        megaMenuInit();
    </script>
    <script src="{{ asset('assets/js/controllers/user.js') }}"></script>
@stop()